#!/bin/bash

mkdir checkpoints/Letter_high/main_model
mkdir checkpoints/Letter_high/main_model/gin_model
mkdir checkpoints/Letter_high/main_model/gin_classifier
mkdir checkpoints/Letter_high/main_model/gat_modules

mkdir checkpoints/Letter_high/fine_tuned_test
mkdir checkpoints/Letter_high/fine_tuned_test/gat_modules
mkdir checkpoints/Letter_high/fine_tuned_test/classifier
mkdir checkpoints/Letter_high/fine_tuned_test/gin_classifier
mkdir checkpoints/Letter_high/fine_tuned_test/gin_model

mkdir checkpoints/TRIANGLES/main_model
mkdir checkpoints/TRIANGLES/main_model/gin_model
mkdir checkpoints/TRIANGLES/main_model/gin_classifier
mkdir checkpoints/TRIANGLES/main_model/gat_modules

mkdir checkpoints/TRIANGLES/fine_tuned_test
mkdir checkpoints/TRIANGLES/fine_tuned_test/gat_modules
mkdir checkpoints/TRIANGLES/fine_tuned_test/classifier
mkdir checkpoints/TRIANGLES/fine_tuned_test/gin_classifier
mkdir checkpoints/TRIANGLES/fine_tuned_test/gin_model